name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Environment properties for the job
    env:
      CI: true
      NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE and sets up Node JS v12 environment
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
          node-version: 14

    - name: Setup Git
      run: 'git config --global url."https://github.com/".insteadOf git@github.com:'

    # Install required dependencies for the build
    - name: Install dependencies
      run: npm ci

    # Run Linters and Ember Tests
    - name: Run tests
      run: npm test